sudo: required
services:
  - docker
language: c
env:
  - IDF_PATH=/esp/esp-idf
  - PATH=$PATH:/esp/xtensa-esp32-elf/bin
before_install:
  - docker pull cylindric/esp-idf
  - docker run -d cylindric/esp-idf
  - docker ps -a
  - docker run cylindric/esp-idf
install:
  - cd Firmware/AquaHub
  - mkdir -p components
  - cd components
  - git clone https://github.com/espressif/arduino-esp32.git arduino
  - ls
  - cd arduino
  - git submodule update --init --recursive
  - ls
  - cd ../..
script:
  - ls /
  - printenv
  - ls
  - make
notifications:
  email:
    on_success: change
    on_failure: change