sudo: required
services:
  - docker
language: c
before_install:
  - docker pull cylindric/esp-idf
  - docker run -dit --name esp-idf -v $(pwd):/src cylindric/esp-idf
  - docker ps -a
script:
  - docker ps -a
  - docker exec -it esp-idf printenv
  - docker exec -it esp-idf bash -c 'cd /src/Firmware ; make'
after_script:
  - docker ps -a
  - docker images
notifications:
  email:
    on_success: change
    on_failure: change