sudo: required
services:
  - docker
language: c
before_install:
  - docker pull cylindric/esp-idf
  - docker run -d --name esp-idf -v $(pwd):/src cylindric/esp-idf
  - docker ps -a
install:
  - cd Firmware/AquaHub
  - mkdir -p components
  - cd components
  - git clone https://github.com/espressif/arduino-esp32.git arduino
  - cd arduino
  - git submodule update --init --recursive
  - cd ../..
script:
  - docker exec -it esp-idf ls /
after_script:
  - docker images
notifications:
  email:
    on_success: change
    on_failure: change