sudo: required
services:
  - docker
language: c
before_install:
  - docker pull cylindric/esp-idf
  - docker run -dit --name esp-idf -v $(pwd):/src cylindric/esp-idf
  - docker ps -a
install:
  - cd Firmware/AquaHub
  - mkdir -p components
  - cd components
  - git clone https://github.com/espressif/arduino-esp32.git arduino
  - cd arduino
  - git submodule update --init --recursive
  - cd ../..
script:
  - docker ps -a
  - docker exec -it esp-idf printenv
  - docker exec -it esp-idf bash -c 'cd /esp/examples/getting-started/hello_world ; make -j5'
  - docker exec -it esp-idf bash -c 'cd /src/Firmware/AquaHub ; make'
after_script:
  - docker ps -a
  - docker images
notifications:
  email:
    on_success: change
    on_failure: change